import Head from "next/head";
import Nav from "@/components/nav";
import Header from "@/components/header";
import Services from "@/components/services";
import About from "@/components/about";
import Contact from "@/components/contact";
import Footer from "@/components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ingerone | Agrimensura </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Nav />
      <Header />
      <Services />
      <About />
      <Contact />
      <Footer />
    </>
  );
}
